config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :projects, only: [:index, :show]
  
  resources :users do
    resources :projects do
      resources :pledges
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :session, only: [:new, :create, :destroy]

  get "signup", to: "users#new", as: "signup"
  get "login", to: "session#new", as: "login"
  get "logout", to: "session#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :pledges 
    has_many :users,  through: :pledges
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :pledges
    has_many :projects, through: :pledges
    has_many :projects
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new

  end

  def index
  end

  def create
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @project.pledges.create(amount: params[:pledge][:amount], user_id: @user.id )
    redirect_to user_project_path(@user, @project)
  end

  def show
  end

  def destroy
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    
  end


  def index
    @projects = Project.all
  end

  def create
    @user = User.find(params[:user_id])
    @user.projects.create(projects_params)
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  def user_show
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    Project.destroy(params[:id])
    redirect_to user_path(@user)
  end

  private
  
  def projects_params
    params.require(:project).permit(:title, :goal)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])

    if @user.nil?
      redirect_to new_user_path
    else
      if @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        redirect_to login_path
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        if session[:user_id].nil? then return false end
        User.find(session[:user_id])
    end
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def admin
        @user = User.find(session[:user_id])
        user_id = @user.id
    end
    
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickstarta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

<!-- Icons -->
<link href="/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
<link href="/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">

<!-- Theme CSS -->
<link type="text/css" href="/assets/css/argon.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
  </head>


  <body>
  <% if current_user%>
      <nav class="flex justify-between bb b--white-10 bg-near-black">
    <a class="link white-70 hover-white no-underline flex items-center pa3" href="">
    <svg
        class="dib h1 w1"
        data-icon="grid"
        viewBox="0 0 32 32"
        style="fill:currentcolor">
        <title>Super Normal Icon Mark</title>
        <path d="M2 2 L10 2 L10 10 L2 10z M12 2 L20 2 L20 10 L12 10z M22 2 L30 2 L30 10 L22 10z M2 12 L10 12 L10 20 L2 20z M12 12 L20 12 L20 20 L12 20z M22 12 L30 12 L30 20 L22 20z M2 22 L10 22 L10 30 L2 30z M12 22 L20 22 L20 30 L12 30z M22 22 L30 22 L30 30 L22 30z">
        </path>
      </svg>
    </a>
    <div class="flex-grow pa3 flex items-center">
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Home", user_path(current_user)%></a>
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "All Projects", projects_path%></a>
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Create new Project", new_user_project_url(current_user) %></a>
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Logout", logout_path%></a>
    </div>
  </nav>
  
  <%else%>
    <nav class="flex justify-between bb b--white-10 bg-near-black">
    <a class="link white-70 hover-white no-underline flex items-center pa3" href="">
    <svg
          class="dib h1 w1"
        data-icon="grid"
        viewBox="0 0 32 32"
        style="fill:currentcolor">
        <title>Super Normal Icon Mark</title>
        <path d="M2 2 L10 2 L10 10 L2 10z M12 2 L20 2 L20 10 L12 10z M22 2 L30 2 L30 10 L22 10z M2 12 L10 12 L10 20 L2 20z M12 12 L20 12 L20 20 L12 20z M22 12 L30 12 L30 20 L22 20z M2 22 L10 22 L10 30 L2 30z M12 22 L20 22 L20 30 L12 30z M22 22 L30 22 L30 30 L22 30z">
        </path>
      </svg>
    </a>
    <div class="flex-grow pa3 flex items-center">
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Login", login_path%></a>
      <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Signup", signup_path%></a>
       <a class="f6 link dib white dim mr3 mr4-ns" href="#0"><%= link_to "Projects", projects_path(@project)%></a>
    </div>
    </nav>
    
  <%end%>
    <%= yield %>

    <!-- Core -->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/popper/popper.min.js"></script>
<script src="/assets/vendor/bootstrap/bootstrap.min.js"></script>

<!-- Theme JS -->
<script src="/assets/js/argon.min.js"></script>
  </body>
</html>

app/views/pledges/create.html.erb
<h1>Pledges#create</h1>
<p>Find me in app/views/pledges/create.html.erb</p>

app/views/pledges/destroy.html.erb
<h1>Pledges#destroy</h1>
<p>Find me in app/views/pledges/destroy.html.erb</p>

app/views/pledges/index.html.erb
<h1>Pledges#index</h1>
<p>Find me in app/views/pledges/index.html.erb</p>

app/views/pledges/new.html.erb
<h1>Pledges#new</h1>
<p>Find me in app/views/pledges/new.html.erb</p>

app/views/pledges/show.html.erb
<h1>Pledges#show</h1>
<p>Find me in app/views/pledges/show.html.erb</p>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/index.html.erb
 

<h1></h1>

<section style="display:grid; grid-template-columns: 25% 25% 25% 25%; text-align:center; padding-left:150px;">
    <%@projects.each do |project|%>
    
    <article class="br2 ba dark-gray b--black-10 mv4 w-100 w-50-m w-25-l mw5 center">
        <div class="pa2 ph3-ns pb3-ns">
            <div class="dt w-100 mt1">
            <div class="dtc">
                <h1 class="f5 f4-ns mv0"><%= link_to project.title, user_project_path(admin, project) %></h1>
            </div>
            <div class="dtc tr">
                <h2 class="f5 mv0">£<%=project.goal%></h2>
            </div>
            </div>
            <p class="f6 lh-copy measure mt2 mid-gray">
            If it fits, i sits burrow under covers. Destroy couch leave hair everywhere,
            and touch water with paw then recoil in horror.
                <h2 class="f5 mv0">This is <%=project.user.name%>'s Project</h2>
            </p>
        </div>
    </article>

    <%end%>
</section>

app/views/projects/new.html.erb
<%= form_with model: [@user, @user.projects.build], local: true do |f|%>
    <%= f.text_field :title, required: true, placeholder:"project title"%>
    <%= f.text_field :goal, required: true, placeholder:"enter a goal"%>
    <%= f.submit "Kickstart project"%>
<%end%>

app/views/projects/show.html.erb
<h1><%=@project.title%></h1>
<h3><%=@project.goal%></h3>

<%= form_with model: [@user, @project, @project.pledges.build], local: true do |pledge|%>
    <%= pledge.text_field :amount, required: true, placeholder:"Pledge amount"%>
    <%= pledge.submit%>
<%end%>

<%= @project.pledges.reduce(0){|t,p| t+=p.amount.to_i}%>



    

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<%= form_with scope: :session, url: session_index_path, local: true do |f|%>
    <%= f.text_field :name, required: true, placeholder:"username"%>
    <%= f.password_field :password, required: true, placeholder:"password"%>
    <%= f.submit "Log In"%>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f|%>
    <%= f.text_field :name, required: true, placeholder:"username"%>
    <%= f.password_field :password, required: true, placeholder:"password"%>
    <%= f.submit%>
<%end%>

app/views/users/show.html.erb
 <a class="link dim black b f1 f-headline-ns tc db mb3 mb4-ns" href="#" title="Home"><%=@user.name%>'s projects</a>


<h1></h1>

<section style="display:grid; grid-template-columns: 25% 25% 25% 25%; text-align:center; padding-left:150px;">
    <%@user.projects.each do |project|%>
    
    <article class="br2 ba dark-gray b--black-10 mv4 w-100 w-50-m w-25-l mw5 center">
        <div class="pa2 ph3-ns pb3-ns">
            <div class="dt w-100 mt1">
            <div class="dtc">
                <h1 class="f5 f4-ns mv0"><%= link_to project.title, user_project_path(@user, project) %></h1>
            </div>
            <div class="dtc tr">
                <h2 class="f5 mv0">£<%=project.goal%></h2>
            </div>
            </div>
            <p class="f6 lh-copy measure mt2 mid-gray">
            If it fits, i sits burrow under covers. Destroy couch leave hair everywhere,
            and touch water with paw then recoil in horror.
            <div><%= link_to "Delete Project", user_project_path(@user, project), method: :delete %></div>
            </p>
        </div>
    </article>

    <%end%>
</section>

<%= link_to "Create new Project", new_user_project_url(@user) %>
<%= link_to "Logout", logout_path%>